baseURL         = "https://ismaelsow.com"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
publishDir = "docs"

[params]
  title       = "Ismaël Sow"
  subtitle    = "Maker - Founder @ Searchness.com"

  cover       = ""
  description = "Musings from Ismaël Sow."
  metaDescription = ""
  customCSS = ["stylesheets/custom.css"]
  RSSLink = ""

  twitterName = "ismaelsow"
  linkedinName = "ismaelsow"

  logo = "images/logo.png"
  orgName = "Ismaël Sow"
  orgWebsite = "https://ismaelsow.com"
  orgDescription = "Ismaël's blog"

  author = "Ismaël Sow"
  authorAvatar = "images/headshot.png"
  authorLocation = "Earth"
  authorWebsite = "https://ismaelsow.com"
  authorDescription = "Maker - Founder @ Searchness"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 199

[[menu.main]]
  name = "User Research Software"
  url = "/user-research-software"
  weight = 198
